import React, { useState, useEffect } from 'react';
import { 
  Maximize2, 
  ExternalLink, 
  Code, 
  Columns, 
  Trash2, 
  MousePointer,
  Eye,
  EyeOff
} from 'lucide-react';
import { SplatItem } from '../types/splat';
import { getSplatPosterUrl } from '../data/defaultSplats';

interface SplatCardProps {
  splat: SplatItem;
  onExplore: (splat: SplatItem) => void;
  onEmbed: (splat: SplatItem) => void;
  onCompareSelect?: (splat: SplatItem) => void;
  onDelete?: (id: string) => void;
  isModalOpen?: boolean;
  globalPreviewEnabled?: boolean;
}

export const SplatCard: React.FC<SplatCardProps> = ({
  splat,
  onExplore,
  onEmbed,
  onCompareSelect,
  onDelete,
  isModalOpen = false,
  globalPreviewEnabled = false,
}) => {
  const [isInteractive, setIsInteractive] = useState(false);
  const [localOverride, setLocalOverride] = useState<boolean | null>(null);

  // Reset local override when the global setting flips
  useEffect(() => {
    setLocalOverride(null);
  }, [globalPreviewEnabled]);

  // Preview is off by default as requested
  const isPreviewActive = localOverride !== null ? localOverride : globalPreviewEnabled;

  // High-resolution WebP poster generated by SuperSplat
  const posterUrl = getSplatPosterUrl(splat);

  // Small card preview: no SuperSplat UI clutter (&noui), live turntable animation
  const cardUrl = React.useMemo(() => {
    let url = splat.url.replace(/[?&]noanim/g, '');
    if (!url.includes('noui')) {
      url = url.includes('?') ? `${url}&noui` : `${url}?noui`;
    }
    return url;
  }, [splat.url]);

  const handleActivatePreview = (e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    setLocalOverride(true);
  };

  const handleDeactivatePreview = (e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    setLocalOverride(false);
    setIsInteractive(false);
  };

  return (
    <article className="relative z-10 bg-white border border-black flex flex-col w-full max-w-full text-black shadow-[4px_4px_0px_#000000]">
      {/* 3D Viewport Box (Square format 1:1, Hardware Accelerated, Black Border) */}
      <div 
        className="relative z-10 w-full aspect-square bg-zinc-100 border-b border-black overflow-hidden select-none"
        style={{ contain: 'strict', isolation: 'isolate', transform: 'translateZ(0)' }}
      >
        {/* Background poster while loading */}
        <div 
          className="absolute inset-0 bg-cover bg-center -z-10 bg-zinc-200"
          style={{ backgroundImage: `url(${posterUrl})` }}
        />

        {/* Live 3D iframe ONLY rendered when preview is active AND fullscreen modal is not open */}
        {isPreviewActive && !isModalOpen ? (
          <>
            <iframe
              src={cardUrl}
              loading="lazy"
              allow="fullscreen; xr-spatial-tracking"
              title={splat.title}
              className={`w-full h-full border-0 block ${
                isInteractive ? 'pointer-events-auto' : 'pointer-events-none'
              }`}
              style={{ transform: 'translateZ(0)' }}
            />

            {/* Direct click to open fullscreen when active and not in orbit lock mode */}
            {!isInteractive && (
              <div
                onClick={() => onExplore(splat)}
                className="absolute inset-0 z-10 cursor-pointer"
                title="Cliquer pour afficher en plein écran"
              />
            )}
          </>
        ) : (
          /* Preview is OFF: Render static high-res snapshot. Fullscreen is completely HIDDEN. */
          <div 
            onClick={() => handleActivatePreview()}
            className="relative w-full h-full cursor-pointer group"
            title="Cliquer pour activer le rendu 3D temps réel"
          >
            <img
              src={posterUrl}
              alt={splat.title}
              className="w-full h-full object-cover select-none"
              loading="lazy"
              onError={(e) => {
                const target = e.currentTarget;
                if (target.src.includes('/v1/')) {
                  target.src = target.src.replace('/v1/', '/v2/');
                } else if (target.src.includes('/v2/')) {
                  target.src = target.src.replace('/v2/', '/v1/');
                }
              }}
            />

            {/* Brutalist Offline / Eco Overlay (NO fullscreen mention) */}
            <div className="absolute inset-0 bg-white/20 hover:bg-white/5 transition-colors flex flex-col items-center justify-center p-4">
              <div className="border border-black bg-white px-3 py-2 text-center shadow-[3px_3px_0px_#000000]">
                <p className="text-[11px] font-mono uppercase tracking-widest text-black font-bold">
                  PRÉVIEW 3D : DÉSACTIVÉE
                </p>
                <p className="text-[10px] font-mono uppercase tracking-wider text-black/70 mt-1">
                  0% GPU · Cliquer pour activer
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Top Floating Controls on Card Viewport */}
        <div className="absolute top-2 right-2 z-20 flex items-center gap-1.5">
          {/* Card-level Masquer / Démasquer Toggle */}
          {isPreviewActive ? (
            <button
              type="button"
              onClick={handleDeactivatePreview}
              title="Masquer le preview 3D de cette carte (Alléger GPU)"
              className="px-2 py-1 border border-black bg-white hover:bg-black hover:text-white text-[11px] font-mono uppercase tracking-wider transition-colors flex items-center gap-1 shadow-[2px_2px_0px_#000000]"
            >
              <EyeOff className="w-3 h-3" />
              <span>MASQUER 3D</span>
            </button>
          ) : (
            <button
              type="button"
              onClick={handleActivatePreview}
              title="Activer la prévisualisation 3D pour cette scène"
              className="px-2 py-1 border border-black bg-black text-white hover:bg-zinc-800 text-[11px] font-mono uppercase tracking-wider transition-colors flex items-center gap-1 shadow-[2px_2px_0px_#000000]"
            >
              <Eye className="w-3 h-3" />
              <span>ACTIVER 3D</span>
            </button>
          )}

          {/* Interactive Orbit Toggle (ONLY visible when 3D preview is active) */}
          {isPreviewActive && (
            <button
              type="button"
              onClick={(e) => {
                e.stopPropagation();
                setIsInteractive(!isInteractive);
              }}
              title={isInteractive ? 'Verrouiller orbite' : 'Activer orbite directe sur la carte'}
              className={`px-2 py-1 border border-black text-[11px] font-mono uppercase tracking-wider transition-colors flex items-center gap-1 shadow-[2px_2px_0px_#000000] ${
                isInteractive 
                  ? 'bg-black text-white'
                  : 'bg-white text-black hover:bg-black hover:text-white'
              }`}
            >
              <MousePointer className="w-3 h-3" />
              <span>{isInteractive ? 'ACTIF' : 'ORBITE'}</span>
            </button>
          )}

          {/* Direct External Link */}
          <a
            href={splat.url}
            target="_blank"
            rel="noreferrer"
            onClick={(e) => e.stopPropagation()}
            title="Ouvrir directement sur superspl.at"
            className="p-1 border border-black bg-white hover:bg-black hover:text-white text-black transition-colors shadow-[2px_2px_0px_#000000]"
          >
            <ExternalLink className="w-3.5 h-3.5" />
          </a>
        </div>
      </div>

      {/* Card Content & Details (Multiple Font Sizes & Clean Black Lines) */}
      <div className="p-4 sm:p-5 flex-1 flex flex-col justify-between bg-white">
        <div>
          {/* Metadata Kicker Strip */}
          <div className="flex flex-wrap items-center justify-between gap-2 text-[10px] font-mono uppercase tracking-widest text-black/60 pb-2 border-b border-black/10 mb-3">
            <span className="font-bold text-black border border-black px-1.5 py-0.5">
              3DGS · RADIANCE
            </span>
            <div className="flex items-center gap-2">
              <span>{splat.splatCount || '1M RADIANCE'}</span>
              <span>·</span>
              <span>{splat.createdAt}</span>
            </div>
          </div>

          {/* Title */}
          <h3 className="text-xl sm:text-2xl font-black uppercase tracking-tight text-black">
            {splat.title}
          </h3>

          {/* Identifier */}
          <p className="text-[11px] font-mono uppercase tracking-wider text-black/50 mt-0.5">
            ID: {splat.supersplatId}
          </p>

          {/* Description */}
          <p className="mt-3 text-xs leading-relaxed text-zinc-700 line-clamp-3">
            {splat.description}
          </p>
        </div>

        {/* Card Footer Actions */}
        <div className="mt-5 pt-4 border-t border-black flex flex-col gap-2">
          {/* Primary Action Button:
              - When preview is OFF: Shows option to turn ON preview. NO FULLSCREEN SHOWN!
              - When preview is ON: Shows FULLSCREEN option!
          */}
          <div className="flex items-center gap-2">
            {isPreviewActive ? (
              <button
                onClick={() => onExplore(splat)}
                className="flex-1 py-2 px-3 border border-black bg-black text-white hover:bg-zinc-800 text-xs font-mono uppercase tracking-wider transition-colors flex items-center justify-center gap-2 shadow-[2px_2px_0px_#000000]"
              >
                <Maximize2 className="w-3.5 h-3.5" />
                <span>EXPLORER EN PLEIN ÉCRAN</span>
              </button>
            ) : (
              <button
                onClick={() => handleActivatePreview()}
                className="flex-1 py-2 px-3 border border-black bg-black text-white hover:bg-zinc-800 text-xs font-mono uppercase tracking-wider transition-colors flex items-center justify-center gap-2 shadow-[2px_2px_0px_#000000]"
              >
                <Eye className="w-3.5 h-3.5" />
                <span>ACTIVER PRÉVISUALISATION 3D</span>
              </button>
            )}

            {/* Secondary Actions */}
            <button
              onClick={() => onEmbed(splat)}
              title="Obtenir le code HTML iframe"
              className="p-2 border border-black bg-white hover:bg-black hover:text-white text-black transition-colors shadow-[2px_2px_0px_#000000]"
            >
              <Code className="w-3.5 h-3.5" />
            </button>

            {onCompareSelect && (
              <button
                onClick={() => onCompareSelect(splat)}
                title="Comparer en écran divisé"
                className="p-2 border border-black bg-white hover:bg-black hover:text-white text-black transition-colors shadow-[2px_2px_0px_#000000]"
              >
                <Columns className="w-3.5 h-3.5" />
              </button>
            )}

            {!splat.isUserOriginal && onDelete && (
              <button
                onClick={() => onDelete(splat.id)}
                title="Supprimer la scène de l'archive"
                className="p-2 border border-black bg-white hover:bg-black hover:text-white text-black transition-colors shadow-[2px_2px_0px_#000000]"
              >
                <Trash2 className="w-3.5 h-3.5" />
              </button>
            )}
          </div>
        </div>
      </div>
    </article>
  );
};

