import React, { useState, useEffect } from 'react';
import { 
  Maximize2, 
  ExternalLink, 
  Code, 
  Columns, 
  Trash2, 
  MousePointer,
  Eye,
  EyeOff,
  Zap
} from 'lucide-react';
import { SplatItem } from '../types/splat';
import { getSplatPosterUrl } from '../data/defaultSplats';

interface SplatCardProps {
  splat: SplatItem;
  onExplore: (splat: SplatItem) => void;
  onEmbed: (splat: SplatItem) => void;
  onCompareSelect?: (splat: SplatItem) => void;
  onDelete?: (id: string) => void;
  isModalOpen?: boolean;
  globalPreviewEnabled?: boolean;
}

export const SplatCard: React.FC<SplatCardProps> = ({
  splat,
  onExplore,
  onEmbed,
  onCompareSelect,
  onDelete,
  isModalOpen = false,
  globalPreviewEnabled = true,
}) => {
  const [isInteractive, setIsInteractive] = useState(false);
  const [localOverride, setLocalOverride] = useState<boolean | null>(null);

  // Reset local override when the global setting flips
  useEffect(() => {
    setLocalOverride(null);
  }, [globalPreviewEnabled]);

  const isPreviewActive = localOverride !== null ? localOverride : globalPreviewEnabled;

  // High-resolution WebP poster generated by SuperSplat
  const posterUrl = getSplatPosterUrl(splat);

  // Small card preview: no UI controls cluttering the card, with live turntable animation running
  const cardUrl = React.useMemo(() => {
    let url = splat.url.replace(/[?&]noanim/g, '');
    if (!url.includes('noui')) {
      url = url.includes('?') ? `${url}&noui` : `${url}?noui`;
    }
    return url;
  }, [splat.url]);

  return (
    <div className="group relative bg-white border border-zinc-200/90 rounded-xl overflow-hidden hover:border-zinc-300 shadow-sm hover:shadow-md transition-all flex flex-col w-full max-w-full">
      {/* 3D Viewport Box with Live Iframe (Square format 1:1, Hardware Accelerated) */}
      <div 
        onClick={() => !isInteractive && onExplore(splat)}
        className={`relative w-full aspect-square bg-black overflow-hidden ${
          !isInteractive ? 'cursor-pointer' : ''
        }`}
        style={{ contain: 'strict', isolation: 'isolate', transform: 'translateZ(0)' }}
        title={!isInteractive ? 'Click to view fullscreen' : undefined}
      >
        {/* Background poster while loading / when modal is open */}
        <div 
          className="absolute inset-0 bg-zinc-950 bg-cover bg-center -z-10"
          style={{ backgroundImage: `url(${posterUrl})` }}
        />

        {/* Render live 3D iframe only when preview is active AND fullscreen modal is not open */}
        {isPreviewActive && !isModalOpen ? (
          <iframe
            src={cardUrl}
            loading="lazy"
            allow="fullscreen; xr-spatial-tracking"
            title={splat.title}
            className={`w-full h-full border-0 block ${
              isInteractive ? 'pointer-events-auto' : 'pointer-events-none'
            }`}
            style={{ transform: 'translateZ(0)' }}
          />
        ) : (
          <div className="relative w-full h-full">
            <img
              src={posterUrl}
              alt={splat.title}
              className="w-full h-full object-cover select-none"
              loading="lazy"
              onError={(e) => {
                const target = e.currentTarget;
                if (target.src.includes('/v1/')) {
                  target.src = target.src.replace('/v1/', '/v2/');
                } else if (target.src.includes('/v2/')) {
                  target.src = target.src.replace('/v2/', '/v1/');
                }
              }}
            />
            {/* Eco Mode indicator overlay */}
            {!isModalOpen && (
              <div className="absolute inset-0 bg-black/15 group-hover:bg-black/35 transition-colors flex flex-col items-center justify-center p-3">
                <div className="opacity-80 group-hover:opacity-100 transition-opacity flex flex-col items-center gap-1.5 text-center pointer-events-none">
                  <div className="p-2.5 rounded-full bg-black/70 backdrop-blur-md border border-white/20 text-white shadow-md">
                    <Maximize2 className="w-4 h-4 text-sky-300" />
                  </div>
                  <span className="text-xs font-semibold text-white drop-shadow">
                    Cliquer pour plein écran
                  </span>
                  <span className="text-[10px] text-emerald-300 font-mono drop-shadow bg-emerald-950/80 px-2 py-0.5 rounded-full border border-emerald-500/30">
                    🍃 Preview masquée · 0% GPU
                  </span>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Direct Click Capture overlay when not in direct orbit mode */}
        {!isInteractive && (
          <div
            onClick={(e) => {
              e.stopPropagation();
              onExplore(splat);
            }}
            className="absolute inset-0 z-10 cursor-pointer"
            title="Click to view fullscreen"
          />
        )}

        {/* Top Floating Controls on Card Viewport */}
        <div className="absolute top-2.5 right-2.5 z-20 flex items-center gap-1.5 opacity-90 hover:opacity-100 transition-opacity">
          {/* Card-level Masquer / Démasquer Toggle */}
          <button
            type="button"
            onClick={(e) => {
              e.stopPropagation();
              setLocalOverride(!isPreviewActive);
              if (isPreviewActive) setIsInteractive(false);
            }}
            title={
              isPreviewActive
                ? 'Masquer le preview 3D de cette carte (Économiser GPU)'
                : 'Démasquer le preview 3D temps réel pour cette scène'
            }
            className={`px-2 py-1 rounded-md text-[11px] font-mono font-medium backdrop-blur transition-all flex items-center gap-1.5 border shadow-sm ${
              isPreviewActive
                ? 'bg-zinc-950/80 hover:bg-zinc-900 border-zinc-700/80 text-zinc-300 hover:text-white'
                : 'bg-emerald-600/90 hover:bg-emerald-500 border-emerald-400 text-white font-semibold'
            }`}
          >
            {isPreviewActive ? (
              <>
                <EyeOff className="w-3 h-3 text-amber-400" />
                <span className="hidden sm:inline">Masquer 3D</span>
              </>
            ) : (
              <>
                <Eye className="w-3 h-3 text-white" />
                <span>Activer 3D</span>
              </>
            )}
          </button>

          {/* Card Direct Interactive Toggle (Only shown when 3D is active) */}
          {isPreviewActive && (
            <button
              type="button"
              onClick={(e) => {
                e.stopPropagation();
                setIsInteractive(!isInteractive);
              }}
              title={isInteractive ? 'Verrouiller défilement (Quitter mode 3D)' : 'Interagir directement dans la carte'}
              className={`px-2.5 py-1 rounded-md text-[11px] font-mono font-medium backdrop-blur transition-all flex items-center gap-1.5 border shadow-sm ${
                isInteractive 
                  ? 'bg-sky-500/90 border-sky-400 text-white'
                  : 'bg-zinc-950/80 border-zinc-700/80 text-zinc-200 hover:text-white hover:bg-zinc-900'
              }`}
            >
              <MousePointer className="w-3 h-3 text-sky-400" />
              <span>{isInteractive ? 'Actif' : 'Orbite'}</span>
            </button>
          )}

          {/* Direct External Link */}
          <a
            href={splat.url}
            target="_blank"
            rel="noreferrer"
            onClick={(e) => e.stopPropagation()}
            title="Open directly in SuperSplat"
            className="p-1 rounded-md bg-zinc-950/80 border border-zinc-700/80 text-zinc-300 hover:text-white backdrop-blur transition-colors"
          >
            <ExternalLink className="w-3.5 h-3.5" />
          </a>
        </div>
      </div>

      {/* Card Content & Details */}
      <div className="p-4 sm:p-5 flex-1 flex flex-col justify-between bg-white">
        <div>
          {/* Quiet Unboxed Metadata Line */}
          <div className="flex items-center gap-2 text-xs text-zinc-500 font-mono mb-1.5">
            <span className="text-sky-600 font-semibold">{splat.category}</span>
            <span aria-hidden="true" className="text-zinc-300">·</span>
            <span>{splat.splatCount || 'Gaussian Splats'}</span>
            <span aria-hidden="true" className="text-zinc-300">·</span>
            <span>{splat.createdAt}</span>
          </div>

          {/* Title */}
          <h3 className="text-base font-bold text-zinc-900 group-hover:text-sky-600 transition-colors">
            {splat.title}
          </h3>

          {/* Description */}
          <p className="mt-2 text-xs text-zinc-600 leading-relaxed line-clamp-2">
            {splat.description}
          </p>
        </div>

        {/* Card Footer & Action Buttons */}
        <div className="mt-5 pt-3.5 border-t border-zinc-100 flex items-center justify-between gap-2">
          {/* Primary Action Button */}
          <button
            onClick={() => onExplore(splat)}
            className="flex-1 py-2 px-3 text-xs font-semibold bg-sky-500 hover:bg-sky-600 text-white rounded-lg transition-colors flex items-center justify-center gap-1.5 shadow-xs"
          >
            <Maximize2 className="w-3.5 h-3.5" />
            <span>Explorer en Plein Écran</span>
          </button>

          {/* Secondary Action Buttons */}
          <div className="flex items-center gap-1">
            <button
              onClick={() => onEmbed(splat)}
              title="Obtenir le code Embed"
              className="p-2 rounded-lg bg-zinc-100 hover:bg-zinc-200 text-zinc-700 border border-zinc-200 transition-colors"
            >
              <Code className="w-3.5 h-3.5" />
            </button>

            {onCompareSelect && (
              <button
                onClick={() => onCompareSelect(splat)}
                title="Comparer en écran divisé"
                className="p-2 rounded-lg bg-zinc-100 hover:bg-zinc-200 text-zinc-700 border border-zinc-200 transition-colors"
              >
                <Columns className="w-3.5 h-3.5" />
              </button>
            )}

            {!splat.isUserOriginal && onDelete && (
              <button
                onClick={() => onDelete(splat.id)}
                title="Supprimer la scène"
                className="p-2 rounded-lg bg-rose-50 hover:bg-rose-100 text-rose-600 border border-rose-200 transition-colors"
              >
                <Trash2 className="w-3.5 h-3.5" />
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
